In [2]:
import os

print("Current folder:")
print(os.getcwd())

print("\nCleaned folder contents:")
print(os.listdir("../data/cleaned"))

Current folder:
c:\Users\piyus\Desktop\Data Analysts  projects\AI-Powered E-Commerce Data Analyst\notebooks

Cleaned folder contents:
['cleaned_superstore.csv']

In [3]:
import pandas as pd
import sqlite3
import os

# Load cleaned data
df = pd.read_csv(
    "../data/cleaned/cleaned_superstore.csv",
    encoding="latin1"
)

print("Cleaned data loaded!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

# Create database
db_path = "../data/superstore.db"

connection = sqlite3.connect(db_path)

# Create SQL table
df.to_sql(
    "sales",
    connection,
    if_exists="replace",
    index=False
)

connection.close()

print("SQLite database created successfully!")
print("Database location:", os.path.abspath(db_path))

Cleaned data loaded!
Rows: 9994
Columns: 26
SQLite database created successfully!
Database location: c:\Users\piyus\Desktop\Data Analysts  projects\AI-Powered E-Commerce Data Analyst\data\superstore.db

In [4]:
import os

print("Files inside data folder:")
print(os.listdir("../data"))

Files inside data folder:
['cleaned', 'raw', 'superstore.db']

In [5]:
connection = sqlite3.connect("../data/superstore.db")

tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    connection
)

display(tables)

connection.close()

    name
0  sales

In [6]:
import sqlite3
import pandas as pd

connection = sqlite3.connect("../data/superstore.db")

print("Connected to SQLite database successfully!")

Connected to SQLite database successfully!

In [7]:
tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table';
    """,
    connection
)
display(tables)

    name
0  sales

In [8]:
query = """
SELECT *
FROM sales
LIMIT 10;
"""
result = pd.read_sql_query(query, connection)
display(result)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Month_Name,Quarter,Profit_Margin
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,November,4,16.00
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,November,4,30.00
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,June,2,47.00
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,October,4,-40.00
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,October,4,11.25
5,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694,2014,6,June,2,29.00
6,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Newell 322,7.2800,4,0.00,1.9656,2014,6,June,2,27.00
7,8,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152,2014,6,June,2,10.00
8,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825,2014,6,June,2,31.25
9,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700,2014,6,June,2,30.00

In [9]:
query = """
SELECT
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales;
"""

result = pd.read_sql_query(query, connection)

display(result)

   Total_Sales  Total_Profit
0   2297200.86     286397.02

In [10]:
query = """
SELECT
    Category,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql_query(query, connection)

display(result)

          Category  Total_Sales  Total_Profit
0       Technology    836154.03     145454.95
1        Furniture    741999.80      18451.27
2  Office Supplies    719047.03     122490.80

In [11]:
query = """
SELECT
    Region,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql_query(query, connection)

display(result)

    Region  Total_Sales  Total_Profit
0     West    725457.82     108418.45
1     East    678781.24      91522.78
2  Central    501239.89      39706.36
3    South    391721.91      46749.43

In [12]:
query = """
SELECT
    "Product Name",
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales
GROUP BY "Product Name"
ORDER BY Total_Sales DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, connection)

display(result)

,Product Name,Total_Sales,Total_Profit
0,Canon imageCLASS 2200 Advanced Copier,61599.82,25199.93
1,Fellowes PB500 Electric Punch Plastic Comb Bin...,27453.38,7753.04
2,Cisco TelePresence System EX90 Videoconferenci...,22638.48,-1811.08
3,HON 5400 Series Task Chairs for Big and Tall,21870.58,0.00
4,GBC DocuBind TL300 Electric Binding System,19823.48,2233.51
5,GBC Ibimaster 500 Manual ProClick Binding System,19024.50,760.98
6,Hewlett Packard LaserJet 3310 Copier,18839.69,6983.88
7,HP Designjet T520 Inkjet Large Format Printer ...,18374.90,4094.98
8,GBC DocuBind P400 Electric Binding System,17965.07,-1878.17
9,High Speed Automatic Electric Letter Opener,17030.31,-262.00

In [13]:
query = """
SELECT
    "Product Name",
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales
GROUP BY "Product Name"
HAVING Total_Profit < 0
ORDER BY Total_Profit ASC
LIMIT 10;
"""

result = pd.read_sql_query(query, connection)

display(result)

,Product Name,Total_Sales,Total_Profit
0,Cubify CubeX 3D Printer Double Head Print,11099.96,-8879.97
1,Lexmark MX611dhe Monochrome Laser Printer,16829.90,-4589.97
2,Cubify CubeX 3D Printer Triple Head Print,7999.98,-3839.99
3,Chromcraft Bull-Nose Wood Oval Conference Tabl...,9917.64,-2876.12
4,Bush Advantage Collection Racetrack Conference...,9544.73,-1934.40
5,GBC DocuBind P400 Electric Binding System,17965.07,-1878.17
6,Cisco TelePresence System EX90 Videoconferenci...,22638.48,-1811.08
7,Martin Yale Chadless Opener Electric Letter Op...,16656.20,-1299.18
8,Balt Solid Wood Round Tables,6518.75,-1201.06
9,BoxOffice By Design Rectangular and Half-Moon ...,1706.25,-1148.44

In [14]:
query = """
SELECT
    Segment,
    COUNT(DISTINCT "Customer ID") AS Customers,
    COUNT(DISTINCT "Order ID") AS Orders,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales
GROUP BY Segment
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql_query(query, connection)

display(result)

       Segment  Customers  Orders  Total_Sales  Total_Profit
0     Consumer        409    2586   1161401.34     134119.21
1    Corporate        236    1514    706146.37      91979.13
2  Home Office        148     909    429653.15      60298.68

In [15]:
query = """
SELECT
    Discount,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    COUNT(*) AS Transactions
FROM sales
GROUP BY Discount
ORDER BY Discount;
"""

result = pd.read_sql_query(query, connection)

display(result)

    Discount  Total_Sales  Total_Profit  Transactions
0       0.00   1087908.47     320987.60          4798
1       0.10     54369.35       9029.18            94
2       0.15     27558.52       1418.99            52
3       0.20    764594.37      90337.31          3657
4       0.30    103226.65     -10369.28           227
5       0.32     14493.46      -2391.14            27
6       0.40    116417.78     -23057.05           206
7       0.45      5484.97      -2493.11            11
8       0.50     58918.54     -20506.43            66
9       0.60      6644.70      -5944.66           138
10      0.70     40620.28     -40075.36           418
11      0.80     16963.76     -30539.04           300

In [16]:
query = """
SELECT
    Category,
    ROUND(SUM(Sales), 2) AS Sales,
    ROUND(SUM(Profit), 2) AS Profit,
    ROUND(
        SUM(Profit) * 100.0 /
        NULLIF(SUM(Sales), 0),
        2
    ) AS Profit_Margin_Percent
FROM sales
GROUP BY Category
ORDER BY Profit_Margin_Percent DESC;
"""

result = pd.read_sql_query(query, connection)

display(result)

          Category      Sales     Profit  Profit_Margin_Percent
0       Technology  836154.03  145454.95                  17.40
1  Office Supplies  719047.03  122490.80                  17.04
2        Furniture  741999.80   18451.27                   2.49

In [ ]:
connection.close()
print("Database connection closed.")